const div = document.createElement("div");
div.className = "main";
const textAdd = document.createTextNode("Ram Ram laddle");
div.style.width = "300px";
div.style.padding = "15px";
div.style.fontSize = "40px";
div.style.backgroundColor = "#463f3a";
div.style.color = "#f4f3ee";
div.style.boxShadow = "0px 0px 100px #e0afa0";
div.style.borderRadius = "20px";
div.appendChild(textAdd);
document.body.appendChild(div);
